### ISSUE TITLE
Incompatible with styled-components

### ISSUE THREAD

**Issue by unicornware** [storybookjs/testing-react#36]
**Describe the bug**

Despite following the [global config][1] instructions, my [`ThemeProvider`][2] is not passing the `theme` prop to its consumers, thus causing several test failures.

**To Reproduce**
1. Create a Storybook project using [styled-components][3]
   
   Example component:

   ```tsx
      /**
       * @file Implementation - Input
       * @module ui/lib/atoms/Input/impl
       */

      const Input: SC<Props, 'input'> = s.input<Props>(p => {
        const sm = p.$size === 'sm'
      
        return css`
          appearance: none; // Fix appearance for date inputs in Safari
          background-clip: padding-box;
          background-color: ${p.theme.settings.inputs.$bg};
          border-color: ${p.theme.settings.inputs.$borderColor};
          border-radius: ${p.theme.settings.inputs.$borderRadius};
          border-style: solid;
          border-width: ${p.theme.settings.inputs.$borderWidth};
          box-shadow: ${p.theme.settings.inputs.$boxShadow};
          color: ${p.theme.settings.inputs.$color};
          font-family: ${p.theme.settings.inputs.$fontFamily};
          font-size: ${p.theme.settings.inputs.$fontSize};
          font-weight: ${p.theme.settings.inputs.$fontWeight};
          height: ${p.theme.space[sm ? 32 : 48]};
          line-height: ${p.theme.settings.inputs.$lineHeight};
          padding: ${p.theme.settings.inputs.$py} ${p.theme.settings.inputs.$px};
          transition: ${p.theme.settings.inputs.$transition};
          width: ${p.theme.size.fluid};
      
          // Placeholders
          &::placeholder {
            font-family: ${p.theme.inputs.placeholder.fontFamily};
            font-size: ${p.theme.fontSizes.sm};
          }
      
          // Customize the focus state to imitate native WebKit styles
          &:focus {
            background-color: ${p.theme.settings.inputs['$bg:focus']};
            border-color: ${p.theme.settings.inputs['$borderColor:focus']};
            box-shadow: ${p.theme.settings.inputs['$borderColor:focus']};
            color: ${p.theme.settings.inputs['$color:focus']};
            font-weight: ${p.theme.settings.inputs['$fontWeight:focus']};
            outline: ${p.theme.space[0]};
          }
        `
      })
   ```
2. Add a `ThemeProvider` to your Storybook preview configuration
   
   ```tsx
      import { ThemeProvider } from 'styled-components'
      import THEME from '../src/styles/theme'

      /**
       * @file Storybook Preview Configuration
       * @module storybook/preview
       */

      export const decorators: DecoratorFn[] = [
        /**
         * Wraps the current story in a `ThemeProvider`.
         *
         * @param {Story} StoryFn - Current story
         * @return {StoryFnReactReturnType} Story wrapped in `ThemeProvider`
         */
        (StoryFn: Story): StoryFnReactReturnType => (
          <ThemeProvider theme={THEME}>
            <StoryFn />
          </ThemeProvider>
        )
      ]

    ```
3. Follow [global config][1] instructions
4. Add a test file
  
    ```tsx
    import { render } from '@testing-library/react'
    import Input from '../Input'
    
    /**
     * @file Unit Tests - Input
     * @module ui/lib/atoms/Input/tests/unit
     * @see https://www.newline.co/fullstack-react/30-days-of-react/day-22
     */
    
    describe('unit:ui/lib/atoms/Input', () => {
      describe('html', () => {
        it('should render <input> element', () => {
          // Act
          const { container } = render(<Input />)
    
          // Expect
          expect(container.firstChild?.nodeName.toLowerCase()).toBe('input')
        })
      })
    })
    ```
4. Run Jest
5. See error
   
    ```zsh
    Summary of all failing tests
     FAIL  packages/ui/src/lib/atoms/Input/__tests__/Input.spec.tsx (18.316 s)
      ● unit:ui/lib/atoms/Input › html › should render <input> element
    
        TypeError: Cannot read property 'inputs' of undefined
    
          40 |     &::placeholder {
          41 |       font-family: ${p.theme.inputs.placeholder.fontFamily};
        > 42 |       font-size: ${p.theme.fontSizes.sm};
             |                                          ^
          43 |     }
          44 |
          45 |     // Customize the focus state to imitate native WebKit styles
    
          at id (packages/ui/src/lib/atoms/Input/Input.tsx:42:42)
          at me (node_modules/styled-components/src/models/Keyframes.js:20:51)
          at e.id [as generateAndInjectStyles] (node_modules/styled-components/src/utils/isStaticRules.js:6:54)
          at id (node_modules/styled-components/src/models/Keyframes.js:20:51)
          at id (node_modules/styled-components/src/models/Keyframes.js:20:51)
          at I (node_modules/styled-components/src/models/Keyframes.js:20:51)
          at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
          at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:17044:20)
          at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19098:16)
          at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
          at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
          at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
          at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
          at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
          at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
          at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
          at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
          at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
          at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
          at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
          at node_modules/react-dom/cjs/react-dom.development.js:26021:7
          at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
          at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
          at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
          at node_modules/@testing-library/react/dist/pure.js:101:25
          at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
          at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
          at Object.render (node_modules/@testing-library/react/dist/pure.js:97:26)
          at Object.<anonymous> (packages/ui/src/lib/atoms/Input/__tests__/Input.spec.tsx:20:43)
    ```

**Expected behavior**

The `theme` prop should be passed down to all context consumers.

**Screenshots**

N/A

**Additional context**

- I can't share the project repo because it's for work
- The project is setup as monorepo using Yarn Workspaces
- To run my tests, I'm using the command syntax `yarn workspace <workspace-name> <command>`
- Prior to attempting to integrate `@storybook/testing-react`, **all** of my tests passed
  - To render components with the `ThemeProvider`, I used a utility function:
 
      ```tsx
        import type { RenderOptions, RenderResult } from '@testing-library/react'
        import { render as renderComponent } from '@testing-library/react'
        import type { ThemeProviderProps } from '@ui/providers/ThemeProvider'
        import { ThemeProvider } from 'styled-components'
        import THEME from '@ui/styles/theme'
        import type { ReactElement } from 'react'
        
        /**
         * @file Test Utilities - @ui
         * @module tests/utils/ui
         */
        
        /**
         * Renders a test component wrapped in the `ThemeProvider`.
         *
         * @param {ReactElement} [ui] - Component to render
         * @param {ThemeProviderProps} [props] - `ThemeProvider` properties
         * @param {RenderOptions} [options] - Render options
         * @return {RenderResult} Render result
         */
        export const render = (
          ui: ReactElement = <>{null}</>,
          props: ThemeProviderProps = { theme: THEME },
          options: RenderOptions = {}
        ): ReturnType<typeof renderComponent> => {
          return renderComponent(
            <ThemeProvider {...{ ...props, children: ui }} />,
            options
          )
        }
       ```

[1]: https://github.com/storybookjs/testing-react#global-config
[2]: https://styled-components.com/docs/api#themeprovider
[3]: https://styled-components.com

**Comment by yannbf** [comment]
Hey @lexusdrumgold thanks for using @storybook/testing-react!

Are the code samples of your test exactly like your test? If so, it seems like you're not really using the library, which explains why the decorators are not being applied.

Here's a possible example of a working code, supposing that you have a `Input.stories.tsx` file, and a story called `Basic`, for instance:

```diff
import { render } from '@testing-library/react'
+import { composeStories } from '@storybook/testing-react'
+import * as stories from '../Input.stories'
-import Input from '../Input'

+const { Basic } = composeStories(stories)

/**
 * @file Unit Tests - Input
 * @module ui/lib/atoms/Input/tests/unit
 * @see https://www.newline.co/fullstack-react/30-days-of-react/day-22
 */

describe('unit:ui/lib/atoms/Input', () => {
  describe('html', () => {
    it('should render <input> element', () => {
      // Act
-      const { container } = render(<Input />)
+      const { container } = render(<Basic />)

      // Expect
      expect(container.firstChild?.nodeName.toLowerCase()).toBe('input')
    })
  })
})
```

Could you try adjusting your tests like that and come back with feedback?

**Comment by lexusdrumgold** [comment]
> Hey @lexusdrumgold thanks for using @storybook/testing-react!
> 
> Are the code samples of your test exactly like your test? If so, it seems like you're not really using the library, which explains why the decorators are not being applied.
> 
> Here's a possible example of a working code, supposing that you have a `Input.stories.tsx` file, and a story called `Basic`, for instance:
> 
> ```diff
> import { render } from '@testing-library/react'
> +import { composeStories } from '@storybook/testing-react'
> +import * as stories from '../Input.stories'
> -import Input from '../Input'
> 
> +const { Basic } = composeStories(stories)
> 
> /**
>  * @file Unit Tests - Input
>  * @module ui/lib/atoms/Input/tests/unit
>  * @see https://www.newline.co/fullstack-react/30-days-of-react/day-22
>  */
> 
> describe('unit:ui/lib/atoms/Input', () => {
>   describe('html', () => {
>     it('should render <input> element', () => {
>       // Act
> -      const { container } = render(<Input />)
> +      const { container } = render(<Basic />)
> 
>       // Expect
>       expect(container.firstChild?.nodeName.toLowerCase()).toBe('input')
>     })
>   })
> })
> ```
> 
> Could you try adjusting your tests like that and come back with feedback?

Thanks for the quick reply! I have a few work tasks to complete, so I'll give your snippet a spin and get back to you later this week!

**Comment by yannbf** [comment]
Hey @unicornware I hope you don't mind, but I'll be closing this issue. Please give a try in the suggestion I gave, I'm confident it will fix your issues. In case it won't, feel free to comment here and I will gladly reopen the issue :)
